---
- name: Download K3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io/
    timeout: 120
    dest: /usr/local/bin/k3s-install.sh
    owner: root
    group: root
    mode: 0755

- name: Disable UFW
  community.general.ufw:
    state: disabled

- name: Create sysctl config
  template:
    src: 90-kubelet.conf.j2
    dest: /etc/sysctl.d/90-kubelet.conf
  notify: Reload sysctl

- name: Run K3S install script
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s-install.sh
  environment:
    INSTALL_K3S_SKIP_START: "true"
    INSTALL_K3S_SKIP_ENABLE: "true"
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
  changed_when: true
